version: "3"

services:
  thor:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - ADMIN_SECRET=secrett
    volumes:
      - ./volumes/data:/data
      - ./volumes/config:/config