version: "3"

services:
  thor:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - ADMIN_SECRET=secrett
    volumes:
      - ./data:/data