name: Upload to ghrc.io

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
      BASE_IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.BASE_IMAGE }}:${{ env.TAG }},${{ env.BASE_IMAGE }}:latest
